#include "ReportGenerator.h"
#include <fstream>
#include <sstream>
#include <iostream>
#include <ctime>
#include <iomanip>
#include <map>

ReportGenerator::ReportGenerator(Database& db, EvidenceTracker& tracker)
    : db(db), tracker(tracker) {}

std::string ReportGenerator::sep(char c, int len) {
    return std::string(len, c) + "\n";
}

std::string ReportGenerator::nowStr() {
    std::time_t now = std::time(nullptr);
    char buf[32];
    std::strftime(buf, sizeof(buf), "%Y-%m-%d %H:%M:%S", std::localtime(&now));
    return std::string(buf);
}

std::string ReportGenerator::formatSize(long long bytes) {
    if (bytes == 0) return "N/A";
    if (bytes < 1024)       return std::to_string(bytes) + " B";
    if (bytes < 1048576)    return std::to_string(bytes / 1024) + " KB";
    if (bytes < 1073741824) return std::to_string(bytes / 1048576) + " MB";
    return std::to_string(bytes / 1073741824) + " GB";
}

// ── Court-ready Case Report ───────────────────────────────────────
std::string ReportGenerator::generateCaseReport(const std::string& caseId,
                                                 const std::string& investigator,
                                                 const std::string& filename) {
    auto evidence    = db.searchEvidenceByCase(caseId);
    auto allCustody  = db.fetchCustodyLogs();

    std::ofstream out(filename);
    if (!out.is_open()) {
        std::cerr << "[REPORT] Cannot open: " << filename << "\n";
        return "";
    }

    std::ostringstream oss; // also build a return string for GUI display

    auto write = [&](const std::string& s) {
        out << s;
        oss << s;
    };

    write(sep());
    write("          DIGITAL FORENSIC EVIDENCE REPORT\n");
    write("              [COURT-READY DOCUMENT]\n");
    write(sep());
    write("  Jurisdiction       : [To be filled by submitting officer]\n");
    write("  Case Number        : " + caseId + "\n");
    write("  Lead Investigator  : " + investigator + "\n");
    write("  Evidence Items     : " + std::to_string(evidence.size()) + "\n");
    write("  Report Generated   : " + nowStr() + "\n");
    write("  Classification     : CONFIDENTIAL — FOR OFFICIAL USE ONLY\n");
    write(sep());
    write("\n  DISCLAIMER: This report has been generated by the Digital Evidence\n");
    write("  Tracker system. All timestamps are system-local time. Evidence\n");
    write("  integrity is verified via SHA-256 cryptographic hashing.\n");
    write("  Digital signatures use RSA-2048 with SHA-256.\n\n");

    // ── Section 1: Evidence Records ───────────────────────────────
    write(sep('-'));
    write("  SECTION 1 — EVIDENCE INVENTORY\n");
    write(sep('-'));

    if (evidence.empty()) {
        write("  [No evidence records found for this case.]\n");
    } else {
        int itemNo = 1;
        for (auto& e : evidence) {
            // Re-verify integrity live
            std::string integrity = tracker.checkIntegrity(e.id);

            write("\n  Item #" + std::to_string(itemNo++) + "\n");
            write("  " + sep('-', 60));
            write("  Evidence ID        : EV-" + std::to_string(e.id) + "\n");
            write("  Case ID            : " + e.caseId + "\n");
            write("  Description        : " + e.description + "\n");
            write("  Location / Source  : " + e.location + "\n");
            write("  Keywords           : " + (e.keywords.empty() ? "—" : e.keywords) + "\n");
            write("  Added By           : " + e.addedBy + "\n");
            write("  Date/Time Added    : " + e.timestamp + "\n");
            write("\n  FILE METADATA:\n");
            write("  Original Filename  : " + (e.filePath.empty()    ? "—" : e.filePath) + "\n");
            write("  MIME Type          : " + (e.mimeType.empty()    ? "—" : e.mimeType) + "\n");
            write("  File Size          : " + formatSize(e.fileSize) + "\n");
            write("  Stored Copy        : " + (e.storedPath.empty()  ? "—" : e.storedPath) + "\n");
            write("  SHA-256 Hash       : " + (e.fileHash.empty()    ? "—" : e.fileHash) + "\n");
            write("  Integrity Status   : " + integrity + "\n");
            write("  Tamper Detection   : " + std::string(
                integrity == "TAMPERED" ? "*** TAMPERED — DO NOT ADMIT WITHOUT REVIEW ***" :
                integrity == "OK"       ? "File hash matches original — INTACT" :
                                          "No file attached") + "\n");
        }
    }

    write("\n");

    // ── Section 2: Chain of Custody ───────────────────────────────
    write(sep('-'));
    write("  SECTION 2 — CHAIN OF CUSTODY (with Digital Signature Verification)\n");
    write(sep('-'));

    // Filter custody logs to this case's evidence IDs
    std::vector<int> caseEvidenceIds;
    for (auto& e : evidence) caseEvidenceIds.push_back(e.id);

    bool anyCustody = false;
    for (auto& l : allCustody) {
        for (int eid : caseEvidenceIds) {
            if (l.evidenceId == eid) {
                anyCustody = true;

                // Re-verify signature
                std::string entryText = l.user + "|" + l.role + "|" +
                                        std::to_string(l.evidenceId) + "|" + l.timestamp;
                std::string rawSig = tracker.signEntry(entryText);
                bool sigValid      = tracker.verifyEntry(entryText, rawSig);

                write("\n  Log ID             : CL-" + std::to_string(l.id) + "\n");
                write("  Evidence ID        : EV-" + std::to_string(l.evidenceId) + "\n");
                write("  Officer / User     : " + l.user + "\n");
                write("  Role               : " + l.role + "\n");
                write("  Action             : " + l.action + "\n");
                write("  Date / Time        : " + l.timestamp + "\n");
                write("  RSA-2048 Signature : " + l.sigStatus + "\n");
                write("  Sig. Live Check    : " + std::string(sigValid ? "VALID ✔" : "INVALID ✘") + "\n");
                write("  " + sep('-', 60));
                break;
            }
        }
    }
    if (!anyCustody) write("  [No custody log entries for this case.]\n");

    // ── Section 3: Audit Trail (case-related) ─────────────────────
    write("\n");
    write(sep('-'));
    write("  SECTION 3 — SYSTEM AUDIT TRAIL\n");
    write(sep('-'));
    auto auditLogs = db.fetchAuditLogs();
    if (auditLogs.empty()) {
        write("  [No audit events recorded.]\n");
    } else {
        for (auto& a : auditLogs) {
            write("  [" + a.timestamp + "]  " +
                  a.user + " (" + a.role + ")  →  " +
                  a.action + "  [" + a.result + "]\n");
        }
    }

    // ── Footer ────────────────────────────────────────────────────
    write("\n");
    write(sep());
    write("  CERTIFICATION\n");
    write(sep('-'));
    write("  I certify that this report accurately reflects the digital evidence\n");
    write("  records as stored in the Digital Evidence Tracker system at the\n");
    write("  time of report generation.\n\n");
    write("  Lead Investigator Signature: ______________________________\n\n");
    write("  Date: ________________    Badge/ID: ________________\n\n");
    write(sep());
    write("                       END OF REPORT\n");
    write(sep());

    out.close();
    std::cout << "[REPORT] Case report saved: " << filename << "\n";
    return oss.str();
}

// ── Full Audit Trail Report ───────────────────────────────────────
std::string ReportGenerator::generateAuditReport(const std::string& filename) {
    auto logs = db.fetchAuditLogs();

    std::ofstream out(filename);
    if (!out.is_open()) {
        std::cerr << "[REPORT] Cannot open: " << filename << "\n";
        return "";
    }

    std::ostringstream oss;
    auto write = [&](const std::string& s) { out << s; oss << s; };

    write(sep());
    write("           SYSTEM AUDIT TRAIL REPORT\n");
    write(sep());
    write("  Generated On   : " + nowStr() + "\n");
    write("  Total Events   : " + std::to_string(logs.size()) + "\n");
    write("  Classification : CONFIDENTIAL — FOR OFFICIAL USE ONLY\n");
    write(sep());
    write("\n");

    if (logs.empty()) {
        write("  [No audit events recorded.]\n");
    } else {
        // Group summary by action
        std::map<std::string, int> actionCount;
        for (auto& l : logs) actionCount[l.action]++;
        write("  ACTION SUMMARY:\n");
        for (auto& [action, count] : actionCount)
            write("    " + action + ": " + std::to_string(count) + "\n");
        write("\n" + sep('-'));
        write("  FULL EVENT LOG (newest first):\n" + sep('-'));

        int seq = 1;
        for (auto& l : logs) {
            write("  [" + std::to_string(seq++) + "] " +
                  l.timestamp + "  |  " +
                  std::string(8 - std::min(8,(int)l.user.size()), ' ') + l.user +
                  " (" + l.role + ")  |  " +
                  l.action + "  →  " + l.result + "\n");
        }
    }

    write("\n" + sep());
    write("              END OF AUDIT REPORT\n");
    write(sep());

    out.close();
    std::cout << "[REPORT] Audit report saved: " << filename << "\n";
    return oss.str();
}

// ── Full Inventory Report ─────────────────────────────────────────
std::string ReportGenerator::generateFullInventory(const std::string& filename) {
    auto all = db.fetchAllEvidence();

    std::ofstream out(filename);
    if (!out.is_open()) return "";

    std::ostringstream oss;
    auto write = [&](const std::string& s) { out << s; oss << s; };

    write(sep());
    write("         COMPLETE EVIDENCE INVENTORY REPORT\n");
    write(sep());
    write("  Generated On   : " + nowStr() + "\n");
    write("  Total Records  : " + std::to_string(all.size()) + "\n");
    write(sep() + "\n");

    for (auto& e : all) {
        std::string integrity = tracker.checkIntegrity(e.id);
        write("  EV-" + std::to_string(e.id) + "  |  Case: " + e.caseId +
              "  |  " + e.timestamp + "\n");
        write("    Description : " + e.description + "\n");
        write("    Location    : " + e.location + "\n");
        write("    File        : " + (e.filePath.empty() ? "—" : e.filePath) +
              "  (" + formatSize(e.fileSize) + ")  [" + e.mimeType + "]\n");
        write("    SHA-256     : " + (e.fileHash.empty() ? "—" : e.fileHash) + "\n");
        write("    Integrity   : " + integrity + "\n");
        write("    Added By    : " + e.addedBy + "\n");
        write("    Keywords    : " + (e.keywords.empty() ? "—" : e.keywords) + "\n");
        write(sep('-'));
    }

    write("\n" + sep() + "                END OF INVENTORY\n" + sep());
    out.close();
    return oss.str();
}
